[2022-03-06 01:20:30,413] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T01:20:25.074128+00:00 [queued]>
[2022-03-06 01:20:30,446] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T01:20:25.074128+00:00 [queued]>
[2022-03-06 01:20:30,447] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 01:20:30,447] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-06 01:20:30,447] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 01:20:30,486] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): whole_spotify_etl> on 2022-03-06 01:20:25.074128+00:00
[2022-03-06 01:20:30,508] {standard_task_runner.py:52} INFO - Started process 2990 to run task
[2022-03-06 01:20:30,545] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spotify_dag', 'whole_spotify_etl', 'manual__2022-03-06T01:20:25.074128+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmpddak2934', '--error-file', '/tmp/tmp7o8yvh2y']
[2022-03-06 01:20:30,562] {standard_task_runner.py:77} INFO - Job 23: Subtask whole_spotify_etl
[2022-03-06 01:20:31,211] {logging_mixin.py:109} INFO - Running <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T01:20:25.074128+00:00 [running]> on host 7fad89a8527c
[2022-03-06 01:20:31,710] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ing.jlllopezp@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=whole_spotify_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-03-06T01:20:25.074128+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-06T01:20:25.074128+00:00
[2022-03-06 01:20:31,718] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl.py", line 47, in run_spotify_etl
    TOKEN = open('./token.txt').readline().strip()
FileNotFoundError: [Errno 2] No such file or directory: './token.txt'
[2022-03-06 01:20:31,821] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=whole_spotify_etl, execution_date=20220306T012025, start_date=20220306T012030, end_date=20220306T012031
[2022-03-06 01:20:31,897] {standard_task_runner.py:92} ERROR - Failed to execute job 23 for task whole_spotify_etl
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl.py", line 47, in run_spotify_etl
    TOKEN = open('./token.txt').readline().strip()
FileNotFoundError: [Errno 2] No such file or directory: './token.txt'
[2022-03-06 01:20:31,946] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-06 01:20:32,248] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
